name: Linting verification
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Linting verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Lint
        run: pnpm run lint