name: Prettier format
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Prettier format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run prettier